## Testing Data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = "./data/full_netflix_dataset.csv"

# https://www.kaggle.com/datasets/octopusteam/full-netflix-dataset

In [3]:
full_netflix_dataset_df = pd.read_csv(data_path)

In [4]:
full_netflix_dataset_df

,title,type,genres,releaseYear,imdbId,imdbAverageRating,imdbNumVotes,availableCountries
0,The Fifth Element,movie,"Action, Adventure, Sci-Fi",1997.0,tt0119116,7.6,517695.0,"AT, CH, DE"
1,Kill Bill: Vol. 1,movie,"Action, Crime, Thriller",2003.0,tt0266697,8.2,1223453.0,"AE, AL, AO, AT, AU, AZ, BG, BH, BY, CA, CI, CM..."
2,Jarhead,movie,"Biography, Drama, War",2005.0,tt0418763,7.0,211879.0,"AD, AE, AG, AL, AO, AT, AZ, BA, BG, BH, BM, BR..."
3,Unforgiven,movie,"Drama, Western",1992.0,tt0105695,8.2,444499.0,"AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO..."
4,Eternal Sunshine of the Spotless Mind,movie,"Drama, Romance, Sci-Fi",2004.0,tt0338013,8.3,1106519.0,"AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG..."
...,...,...,...,...,...,...,...,...
20191,NaN,tv,NaN,2024.0,NaN,NaN,NaN,"AL, AZ, BA, BG, BY, CY, EE, FR, GF, HU, IT, LT..."
20192,NaN,tv,Drama,2024.0,NaN,NaN,NaN,"AO, CI, CM, CV, GH, GQ, KE, MG, ML, MU, MZ, NE..."
20193,NaN,tv,"Animation, Action & Adventure",2016.0,NaN,NaN,NaN,"FJ, HK, ID, IN, JP, KR, MU, MY, PH, PK, SG, TH..."
20194,NaN,tv,NaN,NaN,NaN,NaN,NaN,"FJ, HK, ID, IN, JP, KR, MU, MY, PH, PK, SG, TH..."
20195,Blippi's Ultimate Bounce House Challenges,tv,NaN,2024.0,tt33769880,NaN,NaN,"AG, AL, AO, AU, AZ, BA, BB, BG, BM, BS, BY, BZ..."

In [ ]:
#social_network_ads_df = pd.read_csv(data_path)
#social_network_ads_df = pd.DataFrame(
    #data=np.c_[social_network_ads_df[['Age', 'EstimatedSalary']], social_network_ads_df['Purchased']],
    #columns=['Age', 'EstimatedSalary', 'Purchased']
#)

**ProjektityÃ¶**  
ProjektityÃ¶ sisÃ¤ltÃ¤Ã¤ kolme pÃ¤Ã¤osaa: datan esikÃ¤sittelyn, tilastollisten menetelmien soveltamisen ja keskeisten lÃ¶ydÃ¶sten visualisoinnin. Datan monipuolisuuden varmistamiseksi jokaisen opiskelijan tulee jakaa linkki datasettiin, jota he kÃ¤yttÃ¤vÃ¤t. Kaksi opiskelijaa ei saa kÃ¤yttÃ¤Ã¤ samaa datasettiÃ¤. Tilastollisen analyysin tehokkuuden takaamiseksi on tÃ¤rkeÃ¤Ã¤ varmistaa, ettÃ¤ tietyt datasetin sarakkeet sisÃ¤ltÃ¤vÃ¤t numeerista dataa. ProjektityÃ¶ tulee suorittaa interaktiivisessa muistikirjassa, jossa on sekÃ¤ Markdown- ettÃ¤ Python-koodisoluja.  

**ProjektityÃ¶ssÃ¤ kÃ¤ytettÃ¤vÃ¤ datasetti:**  
- Et voi kÃ¤yttÃ¤Ã¤ Titanic-datasettiÃ¤, jota on kÃ¤sitelty materiaalissa.  
- Voit hankkia datasetin esimerkiksi Kagglesta (https://www.kaggle.com/datasets) tai muusta avoimesta lÃ¤hteestÃ¤.  
- DatasetissÃ¤ tulee olla riittÃ¤vÃ¤ mÃ¤Ã¤rÃ¤ dataa, vÃ¤hintÃ¤Ã¤n 2000 riviÃ¤.  

**Projektin esittelyvideo:**  
Jokaisen opiskelijan tulee luoda video, jossa he esittelevÃ¤t lÃ¶ydÃ¶ksensÃ¤.  

**Projektin palautus:**  
Jokainen opiskelija palauttaa Moodlessa videon, datasetin ja muistikirjatiedoston (.ipynb).  
Palauta .ipynb-tiedostosi sekÃ¤ linkki videoon ja datasettiin.  

**TehtÃ¤vÃ¤t ja aktiviteetit:**  
KÃ¤ytÃ¤ mielikuvitustasi ja luovuuttasi datasetin esikÃ¤sittelyssÃ¤ ja analysoinnissa. Voit aloittaa seuraavista tehtÃ¤vistÃ¤, mutta voit myÃ¶s tutkia muita tapoja:  

**Datan esikÃ¤sittely**  
- Valitse datasetti ja tutustu siihen. Voit esimerkiksi tarkastella satunnaista nÃ¤ytettÃ¤ datasta sekÃ¤ rivien ja sarakkeiden mÃ¤Ã¤rÃ¤Ã¤.  
- Tarkista, sisÃ¤ltÃ¤Ã¤kÃ¶ datasetti puuttuvia arvoja, ja laske puuttuvan datan osuus. PÃ¤Ã¤tÃ¤ kontekstin perusteella, mitÃ¤ tehdÃ¤ puuttuville arvoille, ja toteuta tarvittavat toimenpiteet.  
- Tunnista ja poista datasetistÃ¤ pÃ¤Ã¤llekkÃ¤iset arvot.  
- Jaa yksi datasetin jatkuvaa numeerista dataa sisÃ¤ltÃ¤vÃ¤ sarake sopiviin luokkiin (kÃ¤ytÃ¤ esimerkiksi `cut`- tai `qcut`-funktiota).  
- Tunnista datasetistÃ¤ poikkeavat arvot (outlierit). Jos datasetissÃ¤ ei ole poikkeavia arvoja, voit satunnaisesti muokata osaa datasta.  
- PÃ¤Ã¤tÃ¤, mitÃ¤ tehdÃ¤ poikkeaville arvoille.  

**Dataobjektit ja attribuuttityypit**  
- Tulosta datasetistÃ¤ sarakkeiden nimet, jotka edustavat nimellisiÃ¤ attribuutteja.  
- Tulosta datasetistÃ¤ sarakkeiden nimet, jotka edustavat binaarisia attribuutteja.  
- Tulosta datasetistÃ¤ sarakkeiden nimet, jotka edustavat jÃ¤rjestettyjÃ¤ attribuutteja (ordinal).  

**Perustilastot**  
Tee NumPyn avulla perustilastollisia operaatioita datasetille. Ohjeena voit laskea seuraavat:  
- Keskiarvo (Mean)  
- Mediaani  
- Keskiarvon hajonta (Standard Deviation)  
- Varianssi  
- Minimi- ja maksimiarvot  
- Summa ja tulo  

**Visualisointi**  
KÃ¤ytÃ¤ Matplotlibia erilaisten kaavioiden ja graafien luomiseen. DatasetistÃ¤si ja analyysistÃ¤si riippuen voit tehdÃ¤ seuraavanlaisia visualisointeja:  
- Viivakaavio (Line Plot)  
- Hajontakaavio (Scatter Plot)  
- PylvÃ¤sdiagrammi (Bar Chart)  
- Histogrammi  
- YmpyrÃ¤diagrammi (Pie Chart)  
- LÃ¤mpÃ¶kartta (Heatmap)  
- 3D-kaavio